# from prj.conf (Nucleo board)
CONFIG_GPIO=y
CONFIG_ADC=n
CONFIG_DAC=n
CONFIG_LOG=y
# CONFIG_LOG_DEFAULT_LEVEL. 3:INFO
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_ASSERT=y
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_ZERO_LATENCY_IRQS=y
CONFIG_LOG_MODE_IMMEDIATE=y

# iMX definitions
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_CONSOLE=y
CONFIG_INPUT=y
CONFIG_FPU=y

# RPMsg service sample integration
CONFIG_PRINTK=y
CONFIG_IPM=y
CONFIG_IPM_LOG_LEVEL_INF=y
CONFIG_TIMESLICE_SIZE=1
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_RPMSG_SERVICE=y
CONFIG_RPMSG_SERVICE_MODE_REMOTE=y
CONFIG_RPMSG_SERVICE_LOG_LEVEL_INF=y
CONFIG_OPENAMP_VENDOR_ADDR_TRANSLATION=n
CONFIG_OPENAMP_MASTER=n

# Add Linux remoteproc-compatible .resource_table to the firmware ELF.
CONFIG_OPENAMP_RSC_TABLE=y
CONFIG_OPENAMP_RSC_TABLE_NUM_RPMSG_BUFF=8
CONFIG_OPENAMP_RSC_TABLE_IPM_RX_ID=1
CONFIG_OPENAMP_RSC_TABLE_IPM_TX_ID=0
